services:
  postgres:
    image: postgres:15
    container_name: studymate_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: studymate_user
      POSTGRES_PASSWORD: studymate_pass
      POSTGRES_DB: studymate_db
    volumes:
      - studymate_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: studymate_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@studymate.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  studymate_postgres_data:
